/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AtualizarController;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Sebastian
 */
public class FrameAtualizar extends javax.swing.JFrame {

    private AtualizarController controller;

    public FrameAtualizar() {
        initComponents();
        controller = new AtualizarController();
        txtcotbtc.setEditable(false);
        txtcoteth.setEditable(false);
        txtcotxrp.setEditable(false);
        txtcotmc1.setEditable(false);
        txtcotmc2.setEditable(false);
        txtcotmc3.setEditable(false);
        txtcotmc1.setVisible(false);
        txtcotmc2.setVisible(false);
        txtcotmc3.setVisible(false);
        lblm1.setVisible(false);
        lblm2.setVisible(false);
        lblm3.setVisible(false);
        updateCotacoes();
        String [] moedas;
        moedas = controller.checkarmoedas();
        
        if(moedas.length >= 4){
            lblm1.setVisible(true);
            txtcotmc1.setVisible(true);
            lblm1.setText(moedas[1]);
            txtcotmc1.setText(moedas[2]);
        }
         if(moedas.length>=8){
            lblm2.setVisible(true);
            txtcotmc2.setVisible(true);
            lblm2.setText(moedas[5]);
            txtcotmc2.setText(moedas[6]);
            
        }
         if(moedas.length>=12){
            lblm3.setVisible(true);
            txtcotmc3.setVisible(true);
            lblm3.setText(moedas[9]);
            txtcotmc3.setText(moedas[10]);
        }
    
    }

    private void updateCotacoes() {
        float cotbtc = controller.cotacaobtc();
        float coteth = controller.cotacaoeth();
        float cotxrp = controller.cotacaoxrp();
        txtcotbtc.setText(Float.toString(cotbtc));
        txtcoteth.setText(Float.toString(coteth));
        txtcotxrp.setText(Float.toString(cotxrp));
    }

    public JTextField getTxtcotbtc() {
        return txtcotbtc;
    }

    public JTextField getTxtcoteth() {
        return txtcoteth;
    }

    public JTextField getTxtcotmc1() {
        return txtcotmc1;
    }

    public JTextField getTxtcotmc2() {
        return txtcotmc2;
    }

    public JTextField getTxtcotmc3() {
        return txtcotmc3;
    }

    public JTextField getTxtcotxrp() {
        return txtcotxrp;
    }

    public void setTxtcotbtc(JTextField txtcotbtc) {
        this.txtcotbtc = txtcotbtc;
    }

    public void setTxtcoteth(JTextField txtcoteth) {
        this.txtcoteth = txtcoteth;
    }

    public void setTxtcotmc1(JTextField txtcotmc1) {
        this.txtcotmc1 = txtcotmc1;
    }

    public void setTxtcotmc2(JTextField txtcotmc2) {
        this.txtcotmc2 = txtcotmc2;
    }

    public void setTxtcotmc3(JTextField txtcotmc3) {
        this.txtcotmc3 = txtcotmc3;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnatualizar = new javax.swing.JButton();
        txtcotbtc = new javax.swing.JTextField();
        txtcoteth = new javax.swing.JTextField();
        txtcotxrp = new javax.swing.JTextField();
        txtcotmc1 = new javax.swing.JTextField();
        txtcotmc2 = new javax.swing.JTextField();
        txtcotmc3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblm1 = new javax.swing.JLabel();
        lblm2 = new javax.swing.JLabel();
        lblm3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnatualizar.setText("Atualizar");
        btnatualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatualizarActionPerformed(evt);
            }
        });

        jLabel1.setText("Bitcoin");

        jLabel3.setText("Ripple");

        lblm1.setText("Moeda config1");

        lblm2.setText("Moeda config2");

        lblm3.setText("Moeda config3");

        jLabel7.setText("Ethereum");

        jLabel8.setText("Novo Valor");

        jMenu1.setText("Menu");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(lblm1)
                    .addComponent(lblm2)
                    .addComponent(lblm3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtcotmc3)
                    .addComponent(txtcotmc2)
                    .addComponent(txtcotmc1)
                    .addComponent(txtcotxrp)
                    .addComponent(txtcoteth)
                    .addComponent(txtcotbtc))
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(btnatualizar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnatualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcotbtc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcoteth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcotxrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcotmc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblm1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcotmc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblm2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcotmc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblm3))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        
        FrameMenu fm = new FrameMenu();
        fm.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jMenu1MouseClicked

    private void btnatualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatualizarActionPerformed

        controller.atualizarCotas();
        updateCotacoes();

    }//GEN-LAST:event_btnatualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAtualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAtualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAtualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAtualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnatualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblm1;
    private javax.swing.JLabel lblm2;
    private javax.swing.JLabel lblm3;
    private javax.swing.JTextField txtcotbtc;
    private javax.swing.JTextField txtcoteth;
    private javax.swing.JTextField txtcotmc1;
    private javax.swing.JTextField txtcotmc2;
    private javax.swing.JTextField txtcotmc3;
    private javax.swing.JTextField txtcotxrp;
    // End of variables declaration//GEN-END:variables
}
