/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.SaldoController;
import java.sql.Array;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author citta
 */
public class FrameSaldo extends javax.swing.JFrame {
    private String cpfusuario;

    public void setTxtareaextrato(JTextArea txtareaextrato) {
        this.txtareaextrato = txtareaextrato;
    }
    
    

    public JTextArea getTxtareasaldo() {
        return txtareasaldo;
    }

    public void setTxtareasaldo(JTextArea txtareasaldo) {
        this.txtareasaldo = txtareasaldo;
    }

    /**
     * Creates new form FrameSaldo
     */
    public FrameSaldo(String cpfusuario) {
        initComponents();
        this.cpfusuario = cpfusuario;
        System.out.println(cpfusuario);
        controller = new SaldoController(this, cpfusuario);
        txtareasaldo.setEditable(false);
         //Puxando valores do ResultSet para variaveis locais 
        ResultSet res = controller.consultarsaldo();
    try {
        if (res.next()) {
            
            String nome = res.getString("nome");
            
            String cpf = res.getString("cpf");
            
            String saldo = res.getString("reais");
            
            String saldobtc = res.getString("bitcoin");
            
            String saldoeth = res.getString("ethereum");
            
            String saldoxrp = res.getString("ripple");
            
            StringBuilder saldoString = new StringBuilder();
            
            saldoString.append("Nome: " +nome + "\n" ).append("CPF: " + cpf + "\n \n")
                    .append("Reais: "+saldo + " \n").append("Bitcoin: "+ saldobtc + "\n")
                    .append("Ethereum: "+saldoeth+"\n").append("Ripple: "+saldoxrp + "\n");
            
            Array moedas = res.getArray("criptos");

            Object[] moedasArray = (Object[]) moedas.getArray();

            String[] Stringarray = Arrays.copyOf(moedasArray, moedasArray.length, String[].class);
            
            if(Stringarray.length >=4){
                String saldom1 = Stringarray[2];
                String abv1 = Stringarray[3];
                saldoString.append(abv1 + ": "+ saldom1 + "\n");
                
            }
            if(Stringarray.length >=8){
                String saldom2 = Stringarray[6];
                String abv2 = Stringarray[7];
                saldoString.append(abv2 + ": "+saldom2 + "\n");
            }
            if(Stringarray.length >=12){
                String saldom3 = Stringarray[10];
                String abv3 = Stringarray[11];
                saldoString.append(abv3 + " "+ saldom3 + "\n");
            }
            
            txtareasaldo.append(saldoString.toString());
            
            
        } else {
            // 
            JOptionPane.showMessageDialog(this, "Erro ao buscar dados");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro de conexão");
        e.printStackTrace();
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblframe = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareasaldo = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtareaextrato = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblframe.setText("   SALDO");
        lblframe.setToolTipText("");

        txtareasaldo.setColumns(20);
        txtareasaldo.setRows(5);
        jScrollPane1.setViewportView(txtareasaldo);

        jButton1.setText("Gerar Extrato");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtareaextrato.setColumns(20);
        txtareaextrato.setRows(5);
        jScrollPane2.setViewportView(txtareaextrato);

        jMenu1.setText("Menu");
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 23, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(lblframe, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblframe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String string = controller.imprimirextrato();
        txtareaextrato.append(string);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
        // TODO add your handling code here:
        FrameMenu fm = new FrameMenu();
        fm.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu1MenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
private SaldoController controller;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblframe;
    private javax.swing.JTextArea txtareaextrato;
    private javax.swing.JTextArea txtareasaldo;
    // End of variables declaration//GEN-END:variables
}
