/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ApagarCriptoController;

/**
 *
 * @author Sebastian
 */
public class FrameApagarCripto extends javax.swing.JFrame {

    private ApagarCriptoController controller;
    /**
     * Creates new form apagacripto
     */
    public FrameApagarCripto() {
        initComponents();
        
        controller = new ApagarCriptoController(this);
        
        String[] moedas;
        moedas = controller.checkarmoedas();
        txtmoeda1.setEditable(false);txtmoeda2.setEditable(false);txtmoeda3.setEditable(false);
        txtmoeda1.setVisible(false);
        txtmoeda2.setVisible(false);
        txtmoeda3.setVisible(false);
        btnapagar1.setVisible(false);
        btnapagar2.setVisible(false);
        btnapagar3.setVisible(false);

        
        if(moedas.length == 0){
            System.out.println("List vazia");
        }
         if(moedas.length >= 4){
            txtmoeda1.setVisible(true);
            txtmoeda1.setText(moedas[1]);
            btnapagar1.setVisible(true);
        }
         if(moedas.length>=8){
            txtmoeda2.setVisible(true);
            txtmoeda2.setText(moedas[5]);
            btnapagar2.setVisible(true);
        }
         if(moedas.length>=12){
            txtmoeda3.setVisible(true);
            txtmoeda3.setText(moedas[9]);
            btnapagar3.setVisible(true);
        }
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtmoeda1 = new javax.swing.JTextField();
        btnapagar1 = new javax.swing.JButton();
        btnapagar2 = new javax.swing.JButton();
        txtmoeda2 = new javax.swing.JTextField();
        btnapagar3 = new javax.swing.JButton();
        txtmoeda3 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Apagar Criptomoeda");

        btnapagar1.setText("Apagar");
        btnapagar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnapagar1ActionPerformed(evt);
            }
        });

        btnapagar2.setText("Apagar");
        btnapagar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnapagar2ActionPerformed(evt);
            }
        });

        btnapagar3.setText("Apagar");
        btnapagar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnapagar3ActionPerformed(evt);
            }
        });

        jMenu1.setText("Menu");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmoeda1)
                            .addComponent(btnapagar1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmoeda2)
                            .addComponent(btnapagar2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmoeda3)
                            .addComponent(btnapagar3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtmoeda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnapagar1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtmoeda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnapagar2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtmoeda3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnapagar3)))
                .addGap(118, 118, 118))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        
        FrameMenu fm = new FrameMenu();
        fm.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jMenu1MouseClicked

    private void btnapagar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnapagar1ActionPerformed
       
        controller.apagarmoeda1();
        FrameMenu fm = new FrameMenu();
        fm.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnapagar1ActionPerformed

    private void btnapagar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnapagar2ActionPerformed
        
        controller.apagarmoeda2();
        FrameMenu fm = new FrameMenu();
        fm.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnapagar2ActionPerformed

    private void btnapagar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnapagar3ActionPerformed
        
        controller.apagarmoeda3();
        FrameMenu fm = new FrameMenu();
        fm.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnapagar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApagarCripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApagarCripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApagarCripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApagarCripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApagarCripto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnapagar1;
    private javax.swing.JButton btnapagar2;
    private javax.swing.JButton btnapagar3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField txtmoeda1;
    private javax.swing.JTextField txtmoeda2;
    private javax.swing.JTextField txtmoeda3;
    // End of variables declaration//GEN-END:variables
}
