/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ComprarCriptoController;
import javax.swing.JTextField;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author citta
 */
public class FrameComprarCripto extends javax.swing.JFrame {
    private String cpflogado;

    public JTextField getTxtsaldo() {
        return txtsaldo;
    }

    public JTextField getTxteth() {
        return txteth;
    }

    public JTextField getTxtxrp() {
        return txtxrp;
    }

    public JTextField getTxtcotripple() {
        return txtcotripple;
    }

    
    
    public void setTxtcotbtc(JTextField txtcotbtc) {
        this.txtcotbtc = txtcotbtc;
    }

    public void setTxtcoteth(JTextField txtcoteth) {
        this.txtcoteth = txtcoteth;
    }

    public void setTxtcotripple(JTextField txtcotripple) {
        this.txtcotripple = txtcotripple;
    }

    public void setTxtsaldo(JTextField txtsaldo) {
        this.txtsaldo = txtsaldo;
    }

    public JTextField getTxtbtc() {
        return txtbtc;
    }

    public JTextField getTxtcotbtc() {
        return txtcotbtc;
    }

    public JTextField getTxtcoteth() {
        return txtcoteth;
    }

    

    public JTextField getTxtcomprabtc() {
        return txtcomprabtc;
    }

    public JTextField getTxtcompraxrp() {
        return txtcompraxrp;
    }

    public JTextField getTxtcomrpaeth() {
        return txtcomrpaeth;
    }
    
    

    /**
     * Creates new form FrameComprarCripto
     */
    public FrameComprarCripto(String cpflogado) {
        initComponents();
        this.cpflogado = cpflogado;
        controller = new ComprarCriptoController(this,cpflogado);
        txtcotbtc.setEditable(false);
        txtcoteth.setEditable(false);
        txtcotbtc.setEditable(false);
        txtsaldo.setEditable(false);
        txtcotripple.setEditable(false);
        txtxrp.setEditable(false);
        txteth.setEditable(false);
        txtbtc.setEditable(false);
       
        //Puxando valores do ResultSet para variaveis locais 
        ResultSet res = controller.consultarsc();
    try {
        if (res.next()) {
            
            float saldo = res.getFloat("reais");
            txtsaldo.setText(Float.toString(saldo));
            
            float saldobtc = res.getFloat("bitcoin");
            txtbtc.setText(Float.toString(saldobtc));
            
            float saldoxrp = res.getFloat("ripple");
            txtxrp.setText(Float.toString(saldoxrp));
            
            float saldoeth = res.getFloat("ethereum");
            txteth.setText(Float.toString(saldoeth));
            
        } else {
            // 
            JOptionPane.showMessageDialog(this, "Erro ao buscar dados");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro de conexão");
        e.printStackTrace();
    }
    float cotbtc = controller.cotacaobtc();
    float coteth = controller.cotacaoeth();
    float cotxrp = controller.cotacaoxrp();
    txtcotbtc.setText(Float.toString(cotbtc));
    txtcoteth.setText(Float.toString(coteth));
    txtcotripple.setText(Float.toString(cotxrp));
    
        
       
        
        
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtsaldo = new javax.swing.JTextField();
        txtcotbtc = new javax.swing.JTextField();
        txtcoteth = new javax.swing.JTextField();
        txtcotripple = new javax.swing.JTextField();
        btncbtc = new javax.swing.JButton();
        btnceth = new javax.swing.JButton();
        btncxrp = new javax.swing.JButton();
        txtbtc = new javax.swing.JTextField();
        txteth = new javax.swing.JTextField();
        txtxrp = new javax.swing.JTextField();
        txtcomprabtc = new javax.swing.JTextField();
        txtcomrpaeth = new javax.swing.JTextField();
        txtcompraxrp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menumenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Veja as Criptomoedas e suas cotações");

        jLabel3.setText("Saldo disponível: ");

        btncbtc.setText("Bitcoin");
        btncbtc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncbtcActionPerformed(evt);
            }
        });

        btnceth.setText("Ethereum");
        btnceth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncethActionPerformed(evt);
            }
        });

        btncxrp.setText("Ripple");
        btncxrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncxrpActionPerformed(evt);
            }
        });

        txteth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtethActionPerformed(evt);
            }
        });

        txtxrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtxrpActionPerformed(evt);
            }
        });

        txtcomrpaeth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcomrpaethActionPerformed(evt);
            }
        });

        txtcompraxrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcompraxrpActionPerformed(evt);
            }
        });

        jButton1.setText("Outras moedas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Confira nossas novas moedas");

        menumenu.setText("Menu");
        menumenu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menumenuMenuSelected(evt);
            }
        });
        jMenuBar1.add(menumenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcoteth, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcotbtc, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnceth)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txteth))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btncbtc, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtbtc, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btncxrp, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtxrp)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtcotripple, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtcomprabtc, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcompraxrp, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcomrpaeth))))
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbtc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcotbtc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncbtc))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnceth)
                            .addComponent(txteth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcoteth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcomrpaeth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btncxrp)
                            .addComponent(txtcotripple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtxrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcompraxrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtcomprabtc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(268, 268, 268))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncbtcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncbtcActionPerformed
        // TODO add your handling code here:
        controller.comprarbtc();
        FrameUsuario fu = new FrameUsuario(cpflogado);
        fu.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btncbtcActionPerformed

    private void txtxrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtxrpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtxrpActionPerformed

    private void menumenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menumenuMenuSelected
        // TODO add your handling code here:
        FrameUsuario fu = new FrameUsuario(cpflogado);
        fu.setVisible(true);
        dispose();
    }//GEN-LAST:event_menumenuMenuSelected

    private void btncethActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncethActionPerformed
        // TODO add your handling code here:
        controller.comprareth();
        FrameUsuario fu = new FrameUsuario(cpflogado);
        fu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btncethActionPerformed

    private void txtcompraxrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcompraxrpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcompraxrpActionPerformed

    private void txtcomrpaethActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcomrpaethActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcomrpaethActionPerformed

    private void btncxrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncxrpActionPerformed
        // TODO add your handling code here:
        controller.comprarxrp();
        FrameUsuario fu = new FrameUsuario(cpflogado);
        fu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btncxrpActionPerformed

    private void txtethActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtethActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtethActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        FrameCriptosNovas fcn = new FrameCriptosNovas(cpflogado);
        fcn.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameComprarCripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameComprarCripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameComprarCripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameComprarCripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
private ComprarCriptoController controller;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncbtc;
    private javax.swing.JButton btnceth;
    private javax.swing.JButton btncxrp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menumenu;
    private javax.swing.JTextField txtbtc;
    private javax.swing.JTextField txtcomprabtc;
    private javax.swing.JTextField txtcompraxrp;
    private javax.swing.JTextField txtcomrpaeth;
    private javax.swing.JTextField txtcotbtc;
    private javax.swing.JTextField txtcoteth;
    private javax.swing.JTextField txtcotripple;
    private javax.swing.JTextField txteth;
    private javax.swing.JTextField txtsaldo;
    private javax.swing.JTextField txtxrp;
    // End of variables declaration//GEN-END:variables
}
