/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;



/**
 *
 * @author citta
 */
public class FrameUsuario extends javax.swing.JFrame {
    private String cpflogado;

    /**
     * Creates new form FrameUsuario
     */
    public FrameUsuario(String cpflogado) {
        initComponents();
        this.cpflogado = cpflogado;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblusuario = new javax.swing.JLabel();
        btnconsultarsaldo = new javax.swing.JButton();
        btndepositar = new javax.swing.JButton();
        btnsacar = new javax.swing.JButton();
        btncomprarcripto = new javax.swing.JButton();
        btnatualizarcotacao = new javax.swing.JButton();
        btnsair = new javax.swing.JButton();
        btnvendercripto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblusuario.setText("Ola Usuario, deseja acessar qual função?");

        btnconsultarsaldo.setText("Consultar Saldo/Gerar Extrato");
        btnconsultarsaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarsaldoActionPerformed(evt);
            }
        });

        btndepositar.setText("Depositar");
        btndepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndepositarActionPerformed(evt);
            }
        });

        btnsacar.setText("Sacar");
        btnsacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsacarActionPerformed(evt);
            }
        });

        btncomprarcripto.setText("Comprar  Cripto");
        btncomprarcripto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomprarcriptoActionPerformed(evt);
            }
        });

        btnatualizarcotacao.setText("Atualizar cotação");
        btnatualizarcotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatualizarcotacaoActionPerformed(evt);
            }
        });

        btnsair.setText("Sair");
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });

        btnvendercripto.setText("Vender Cripto");
        btnvendercripto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvendercriptoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lblusuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btnsair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnconsultarsaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncomprarcripto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnvendercripto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnsacar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndepositar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnatualizarcotacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblusuario)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnconsultarsaldo)
                    .addComponent(btndepositar))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsacar)
                    .addComponent(btncomprarcripto))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnatualizarcotacao)
                    .addComponent(btnvendercripto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnsair)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnconsultarsaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarsaldoActionPerformed
        // TODO add your handling code here:
        FrameSaldo fs = new FrameSaldo(cpflogado);
        fs.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnconsultarsaldoActionPerformed

    private void btndepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndepositarActionPerformed
        // TODO add your handling code here:
        FrameDeposito fd = new FrameDeposito(cpflogado);
        fd.setVisible(true);
        dispose();
    }//GEN-LAST:event_btndepositarActionPerformed

    private void btncomprarcriptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomprarcriptoActionPerformed
        // TODO add your handling code here:
        FrameComprarCripto fcc = new FrameComprarCripto(cpflogado);
        fcc.setVisible(true);
        dispose();
    }//GEN-LAST:event_btncomprarcriptoActionPerformed

    private void btnvendercriptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvendercriptoActionPerformed
        // TODO add your handling code here:
        FrameVendaCripto fv = new FrameVendaCripto(cpflogado);
        fv.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnvendercriptoActionPerformed

    private void btnsacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsacarActionPerformed
        // TODO add your handling code here:
        FrameSaque fs = new FrameSaque(cpflogado);
        fs.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnsacarActionPerformed

    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
       
        dispose();
        
    }//GEN-LAST:event_btnsairActionPerformed

    private void btnatualizarcotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatualizarcotacaoActionPerformed

        FrameAtualizar fa = new FrameAtualizar(cpflogado);
        fa.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnatualizarcotacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnatualizarcotacao;
    private javax.swing.JButton btncomprarcripto;
    private javax.swing.JButton btnconsultarsaldo;
    private javax.swing.JButton btndepositar;
    private javax.swing.JButton btnsacar;
    private javax.swing.JButton btnsair;
    private javax.swing.JButton btnvendercripto;
    private javax.swing.JLabel lblusuario;
    // End of variables declaration//GEN-END:variables
}
